 
 name: NormCI
 
 on: [pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: test_tests
 
 jobs:
   norm:
     runs-on: ubuntu-latest
 
     steps:
       - name: checkout git repository
         uses: actions/checkout@v2
       
       - name: Make test
         run: norminette
