 
 name: NormCI
 
 on: [pull_request, workflow_dispatch]
 
 jobs:
   norm:
     runs-on: ubuntu-latest
 
     steps:
       - name: checkout git repository
         uses: actions/checkout@v2
      
       - name: change directory
         run: cd test_tests
 
       - name: Make test
         run: make test
